In [1]:
import pandas as pd
import numpy as np
import re
import re as reg
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Baca data hasil scrapping dari excel
data = pd.read_excel('JavaHeritageHotel.xlsx')
data

customer_name                  customer_judul_komen  \
0               andy S                     Hotel yang nyaman   
1      Fabian Hernanda                     Keluarga Hernawan   
2        christiandi a  Kamarnya nyaman,kolam renangnya aman   
3           Fajar Heks                           Hotel juara   
4          Yono Suyono                     nyaman dan tenang   
..                 ...                                   ...   
114          Irwan_Joe               Dari dinasti ke horison   
115           Rachel U       Semoga dapat menjadi lebih baik   
116      Anu_Singapore                     Di atas rata-rata   
117       agus budiman                       harga rata-rata   
118  pleasantinterlude        Baik tetapi dapat ditingkatkan   

                              customer_judul_komen_url  \
0    https://www.tripadvisor.co.id/ShowUserReviews-...   
1    https://www.tripadvisor.co.id/ShowUserReviews-...   
2    https://www.tripadvisor.co.id/ShowUserReviews-...   
3    https://www.tripadvisor.co.id/ShowUserReviews-...   
4    https://www.tripadvisor.co.id/ShowUserReviews-...   
..                                                 ...   
114  https://www.tripadvisor.co.id/ShowUserReviews-...   
115  https://www.tripadvisor.co.id/ShowUserReviews-...   
116  https://www.tripadvisor.co.id/ShowUserReviews-...   
117  https://www.tripadvisor.co.id/ShowUserReviews-...   
118  https://www.tripadvisor.co.id/ShowUserReviews-...   

                                    customer_isi_komen  
0    Salah satu hotel yang terbaik di Purwokerto, b...  
1    Mobil Delica Hotel Java Heritage Keluarga Enda...  
2    Hotel ini layak jadi pilihan pertama bila anda...  
3    Hotel juara di purwokerto.... lokasi di tengah...  
4    kemegahan bangunan dan fasilitas penunjang kad...  
..                                                 ...  
114  Ini adalah pertama kalinya saya tinggal di hor...  
115  Pertama saya pilih di bangunan tua yang indah....  
116  Kamar yang luas - hotel yang nyaman. Layanan l...  
117  salah satu hotel terbaik di purwokerto dengan ...  
118  Tinggal di hotel untuk malam. Kesan pertama ad...  

[119 rows x 4 columns]

In [3]:
#Preprocessing
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

slangs={'yg':'yang', 'tdk':'tidak', 'pd':'pada', 'mlh':'malah', 'jgn':'jangan', 'jg':'juga', 'tp':'tapi', 'blkg': 'belakang', 'dr':'dari', 'klo':'kalo', 'lg':'lagi', 'dlm':'dalam', 'dgn':'dengan', 'g':'tiddak', 'aj':'saja',
       'blh':'boleh', 'jg':'juga', 'jd':'jadi', 'lgsg':'langsung'}
processed_comments = []

for sentence in data['customer_isi_komen']:
    # Remove all the special characters
    processed_comment = re.sub(r'\W', ' ', str(sentence))
    
    # Converting to Lowercase
    processed_comment = processed_comment.lower()
    
    #Remove number 
    processed_comment = re.sub(r'\d+', ' ', processed_comment)

    # remove all single characters
    processed_comment = re.sub(r'\s+[a-zA-Z]\s+', ' ', processed_comment)
    
    #remove duplicate character
    pattern=reg.compile(r"(.)\1{1,}",reg.DOTALL)
    processed_comment=pattern.sub(r"\1",processed_comment)


    #Corrected Slang words
    words = processed_comment.split()
    rfrm=[slangs[word] if word in slangs else word for word in words]
    processed_comment= " ".join(rfrm)

    #remove stopword
    factory = StopWordRemoverFactory()
    more_stopword = ['tak', 'jd', 'per', 'nya', 'terjemah', 'diterjemahkan', 'oleh', 'gogle', 'google' ,'nan'] #menambahkan stopword
    stopwords = factory.get_stop_words() + more_stopword
    temp = [t for t in re.findall(r'\b[a-z]+-?[a-z]+\b',processed_comment) if t not in stopwords]
    processed_comment = ' '.join(temp)
    
    #stemming
    stemmer = StemmerFactory().create_stemmer()
    processed_comment = stemmer.stem(processed_comment)
    
    # Substituting multiple spaces with single space
    processed_comment = re.sub(r'\s+', ' ', processed_comment, flags=re.I)

    processed_comments.append(processed_comment)
    
#output data Preprocessing
processed_comments

['salah satu hotel baik purwokerto banyak fasilitas sedia sini pilih kamar banyak kamar tempat cukup luas bersih suka jalan pagi hari keliling hotel sdh cukup buat lelah keluar area hotel pandang roftopnya bagus sarapanya sangat variasi cari lokasi makan sangat banyak terima kasih atas layan bagus',
 'mobil delica hotel java heritage keluarga endah hernawan hajar hernawan audrey vialita hernanda aldy hernanda fabian hernanda rudi driver terima kasih rudi pecat sopir fabian fod and travel asia',
 'hotel layak jadi pilih pertama bila kunjung kota purwokerto lokasi strategis kamar nyaman kolam renang aman dalam jadi hotel layak jadi pilih',
 'hotel juara purwokerto lokasi tengah keliling tempat makan juara lot parkir luas interior instagramable nuansa jawa kamar deluxe luas banding hotel kelas pilih makan lengkap lezat staf ramah responsif atas keluh',
 'megah bangun fasilitas tunjang kadangkala diri sendiri sini java heritage suguh lengkap megah lengkap fasilitas gedung kerapihan kolam r

In [4]:
import nltk

In [5]:
nltk.download("punkt")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [8]:
from nltk.tokenize import word_tokenize

k = processed_comment
kalimat = nltk.sent_tokenize(k)
print ("Kalimat Awal: ", kalimat)
hasil = nltk.word_tokenize(k)
print("Hasil Tokenizing: ", hasil)

Kalimat Awal:  ['tingal hotel malam kesan pertama besar gedung tampak baru awat baik staf sangat tahu sedia bantu minta rekomendasi tempat unjung dapat ruang benar benar besar kamar tepat belah lift milik apa lihat tawar meski jendela hadap koridor belakang kamar handuk mandi tempat kamar mandi kertas toilet sedia cukup yakin milik apa handuk tangan wajah tanya satu beri handuk mandi minta pinjam ering rambut akhir malam habis stock kata periksa']
Hasil Tokenizing:  ['tingal', 'hotel', 'malam', 'kesan', 'pertama', 'besar', 'gedung', 'tampak', 'baru', 'awat', 'baik', 'staf', 'sangat', 'tahu', 'sedia', 'bantu', 'minta', 'rekomendasi', 'tempat', 'unjung', 'dapat', 'ruang', 'benar', 'benar', 'besar', 'kamar', 'tepat', 'belah', 'lift', 'milik', 'apa', 'lihat', 'tawar', 'meski', 'jendela', 'hadap', 'koridor', 'belakang', 'kamar', 'handuk', 'mandi', 'tempat', 'kamar', 'mandi', 'kertas', 'toilet', 'sedia', 'cukup', 'yakin', 'milik', 'apa', 'handuk', 'tangan', 'wajah', 'tanya', 'satu', 'beri', 

# Vektorisasi TF

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
tf_vec = CountVectorizer(max_df=1.0, min_df=1)
tf = tf_vec.fit_transform(hasil)

#Hasil representasi
tf_term = tf_vec.get_feature_names()
print(tf_vec.get_feature_names())
matrix = tf.toarray()
print(matrix)

['akhir', 'apa', 'awat', 'baik', 'bantu', 'baru', 'belah', 'belakang', 'benar', 'beri', 'besar', 'cukup', 'dapat', 'ering', 'gedung', 'habis', 'hadap', 'handuk', 'hotel', 'jendela', 'kamar', 'kata', 'kertas', 'kesan', 'koridor', 'lift', 'lihat', 'malam', 'mandi', 'meski', 'milik', 'minta', 'periksa', 'pertama', 'pinjam', 'rambut', 'rekomendasi', 'ruang', 'sangat', 'satu', 'sedia', 'staf', 'stock', 'tahu', 'tampak', 'tangan', 'tanya', 'tawar', 'tempat', 'tepat', 'tingal', 'toilet', 'unjung', 'wajah', 'yakin']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# Modelling dengan 5 Topik

In [18]:
from sklearn.decomposition import LatentDirichletAllocation as LDA

topik = 5 #utk mendptkn jml topik terbaik perlu trial
lda = LDA(n_components = topik, learning_method = 'batch', random_state = 0).fit(tf)
lda

LatentDirichletAllocation(n_components=5, random_state=0)

In [19]:
#training LDA
vsm_topik = lda.transform(tf)
#tampilkan hasil
print(vsm_topik.shape)
vsm_topik

(69, 5)


array([[0.10002456, 0.10002666, 0.10002197, 0.10003801, 0.5998888 ],
       [0.10002456, 0.10002666, 0.10002197, 0.10003801, 0.5998888 ],
       [0.10001105, 0.10001199, 0.59994964, 0.10001709, 0.10001024],
       [0.10002546, 0.10002763, 0.59988391, 0.10003941, 0.1000236 ],
       [0.10002456, 0.10002666, 0.10002197, 0.10003801, 0.5998888 ],
       [0.59995599, 0.10001072, 0.10000884, 0.10001528, 0.10000916],
       [0.10002546, 0.10002763, 0.59988391, 0.10003941, 0.1000236 ],
       [0.10002546, 0.10002763, 0.59988391, 0.10003941, 0.1000236 ],
       [0.10002098, 0.59990834, 0.10001877, 0.10003246, 0.10001945],
       [0.59989857, 0.10002471, 0.10002037, 0.10003524, 0.10002111],
       [0.10002456, 0.10002666, 0.10002197, 0.10003801, 0.5998888 ],
       [0.10002546, 0.10002763, 0.59988391, 0.10003941, 0.1000236 ],
       [0.59989857, 0.10002471, 0.10002037, 0.10003524, 0.10002111],
       [0.10002456, 0.10002666, 0.10002197, 0.10003801, 0.5998888 ],
       [0.10000911, 0.59996022, 0.

In [20]:
#Tampilan nilai-nilai setiap fitur
print(lda.components_)

[[1.19979724 0.20002557 1.19979724 0.2000491  0.20005089 0.20004194
  1.19979724 0.2000491  0.20003642 0.20004194 2.19982396 0.20002943
  0.2000491  1.19979724 0.20005089 0.2000491  0.2000491  3.19983245
  0.2000491  0.2000491  3.19983245 1.19979724 0.2000491  0.20005089
  0.20002943 0.20005089 0.20004194 0.20004418 0.20003467 0.20002943
  0.20004418 0.20004418 0.2000491  0.2000491  0.20004194 0.20005089
  0.2000491  0.20005089 1.19979724 0.20004194 0.20003642 0.20005089
  0.20002943 0.2000491  0.20005089 1.19979724 0.20005089 0.20004194
  0.20004263 0.20005089 0.2000491  0.20005089 0.2000491  0.20005089
  0.2000491 ]
 [0.20004941 0.20002775 0.20004941 0.20005329 0.20005523 1.19981676
  0.20004941 0.20005329 2.19984089 1.19981676 0.2000429  0.20003194
  0.20005329 0.20004941 0.20005523 0.20005329 0.20005329 0.20004083
  0.20005329 0.20005329 0.20004083 0.20004941 0.20005329 0.20005523
  0.20003194 0.20005523 1.19981676 0.20004795 3.19984856 0.20003194
  0.20004795 0.20004795 0.20005329

In [22]:
#Hasil Label Topic Model setiap Dokumen
import numpy as np
topics = np.argmax(vsm_topik, axis = 1)
topics

array([4, 4, 2, 2, 4, 0, 2, 2, 1, 0, 4, 2, 0, 4, 1, 2, 2, 4, 4, 4, 4, 2,
       1, 1, 0, 0, 2, 0, 2, 2, 3, 1, 1, 3, 4, 4, 3, 4, 0, 0, 1, 4, 0, 1,
       4, 2, 1, 3, 4, 2, 3, 0, 0, 2, 2, 1, 1, 0, 1, 2, 1, 0, 2, 0, 2, 4,
       3, 0, 4], dtype=int64)

In [24]:
#Cetak Word Fitur dgn Nilai Tertinggi pada Setiap Topik
n_top = 4 #Jml Fitur Tertinggi
topik_word = {}

for topic, comp in enumerate(lda.components_):
    word_idx = np.argsort(comp)[::-1][:n_top]
    
    # store the words most relevant to the topic
    topik_word[topic] = [tf_vec.get_feature_names()[i]+' '+str(comp[i]) for i in word_idx]

In [25]:
for topic, words in topik_word.items():
    print('Topic: %d' % topic)
    print(' %s' % ', '.join(words))

Topic: 0
 handuk 3.1998324502498052, kamar 3.1998324502493936, besar 2.199823963682491, akhir 1.1997972358643856
Topic: 1
 mandi 3.199848558589494, sedia 2.199840892816391, benar 2.1998408928136426, pinjam 1.1998167553599777
Topic: 2
 minta 2.199798568740589, milik 2.1997985687375565, malam 2.1997985687343586, gedung 1.1997679483730979
Topic: 3
 apa 2.199900100736936, meski 1.1998849940628298, stock 1.199884994060612, cukup 1.1998849940604905
Topic: 4
 tempat 2.1998070415175768, kertas 1.1997777208021603, tahu 1.1997777207882394, belakang 1.1997777207809426


# Modelling dgn 10 Topik

In [26]:
from sklearn.decomposition import LatentDirichletAllocation as LDA

topik2 = 10 #utk mendptkn jml topik terbaik perlu trial
lda2 = LDA(n_components = topik2, learning_method = 'batch', random_state = 0).fit(tf)
lda2

LatentDirichletAllocation(random_state=0)

In [27]:
#training LDA
vsm_topik2 = lda2.transform(tf)
#tampilkan hasil
print(vsm_topik2.shape)
vsm_topik2

(69, 10)


array([[0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
        0.05      , 0.05      , 0.05      , 0.05      , 0.54999999],
       [0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
        0.05      , 0.05      , 0.05      , 0.05      , 0.54999999],
       [0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
        0.05      , 0.05      , 0.05      , 0.05      , 0.54999999],
       [0.05      , 0.54999999, 0.05      , 0.05      , 0.05      ,
        0.05      , 0.05      , 0.05      , 0.05      , 0.05      ],
       [0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
        0.05      , 0.05      , 0.05      , 0.54999999, 0.05      ],
       [0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
        0.05      , 0.05      , 0.05      , 0.55      , 0.05      ],
       [0.54999999, 0.05      , 0.05      , 0.05      , 0.05      ,
        0.05      , 0.05      , 0.05      , 0.05      , 0.05      ],
       [0.05      , 0.05      , 0.5499999

In [30]:
#Tampilan nilai-nilai setiap fitur
print(lda.components_)

[[1.19979724 0.20002557 1.19979724 0.2000491  0.20005089 0.20004194
  1.19979724 0.2000491  0.20003642 0.20004194 2.19982396 0.20002943
  0.2000491  1.19979724 0.20005089 0.2000491  0.2000491  3.19983245
  0.2000491  0.2000491  3.19983245 1.19979724 0.2000491  0.20005089
  0.20002943 0.20005089 0.20004194 0.20004418 0.20003467 0.20002943
  0.20004418 0.20004418 0.2000491  0.2000491  0.20004194 0.20005089
  0.2000491  0.20005089 1.19979724 0.20004194 0.20003642 0.20005089
  0.20002943 0.2000491  0.20005089 1.19979724 0.20005089 0.20004194
  0.20004263 0.20005089 0.2000491  0.20005089 0.2000491  0.20005089
  0.2000491 ]
 [0.20004941 0.20002775 0.20004941 0.20005329 0.20005523 1.19981676
  0.20004941 0.20005329 2.19984089 1.19981676 0.2000429  0.20003194
  0.20005329 0.20004941 0.20005523 0.20005329 0.20005329 0.20004083
  0.20005329 0.20005329 0.20004083 0.20004941 0.20005329 0.20005523
  0.20003194 0.20005523 1.19981676 0.20004795 3.19984856 0.20003194
  0.20004795 0.20004795 0.20005329

In [31]:
#Hasil Label Topic Model setiap Dokumen
import numpy as np
topics2 = np.argmax(vsm_topik2, axis = 1)
topics2

array([9, 9, 9, 1, 8, 8, 0, 2, 5, 4, 5, 9, 5, 4, 1, 2, 8, 9, 0, 9, 7, 2,
       7, 7, 8, 4, 6, 9, 7, 6, 3, 1, 8, 6, 4, 1, 9, 1, 4, 0, 1, 0, 4, 1,
       9, 2, 1, 8, 4, 6, 3, 0, 6, 2, 3, 7, 5, 0, 1, 8, 1, 0, 4, 2, 9, 4,
       8, 0, 9], dtype=int64)

In [32]:
#Cetak Word Fitur dgn Nilai Tertinggi pada Setiap Topik
n_top2 = 4 #Jml Fitur Tertinggi
topik_word2 = {}

for topic, comp in enumerate(lda2.components_):
    word_idx2 = np.argsort(comp)[::-1][:n_top2]
    
    # store the words most relevant to the topic
    topik_word2[topic] = [tf_vec.get_feature_names()[i]+' '+str(comp[i]) for i in word_idx2]

In [34]:
for topic, words in topik_word2.items():
    print('Topic: %d' % topic)
    print(' %s' % ', '.join(words))

Topic: 0
 handuk 3.0999999838176313, tempat 2.099999982631682, gedung 1.0999999784453474, kata 1.0999999784453474
Topic: 1
 mandi 3.099999981091222, sedia 2.0999999797054634, kesan 1.0999999748138132, pinjam 1.0999999748138132
Topic: 2
 akhir 1.0999999820766007, bantu 1.0999999820766007, ruang 1.0999999820766007, wajah 1.0999999820766007
Topic: 3
 apa 2.0999999899458697, tanya 1.099999987522495, kertas 0.10000000412030527, koridor 0.10000000412030527
Topic: 4
 kamar 3.0999999824544475, tahu 1.099999976629608, yakin 1.0999999766296078, rambut 1.0999999766296078
Topic: 5
 sangat 1.0999999857073863, beri 1.099999985707386, baik 1.099999985707386, baru 1.099999985707386
Topic: 6
 milik 2.099999987020543, tangan 1.099999983892069, meski 1.099999983892069, tepat 1.099999983892069
Topic: 7
 benar 2.099999987020543, satu 1.099999983892069, lift 1.099999983892069, dapat 1.099999983892069
Topic: 8
 minta 2.099999982631682, besar 2.099999982631682, pertama 1.0999999784453476, tawar 1.099999978445

# Kesimpulan
Data komentar pada Java Heritage Hotel Purwokerto, diperoleh hasil TOpic Modelling menggunakan LDA, sbb:
1. Diambil 5 topik
Diperoleh munculnya topik, yaitu: handul, mandi, minta, apa, tempat
2. Diambil 10 topik
Diperoleh munculnya topik, yaitu: mandi, akhir, apa, kamar, sangat,milik, benar, minta, malamP